### ISSUE TITLE
Update README and suggested versions

### ISSUE THREAD

**Issue by nzjrs** [MatteoH2O1999/setup-python#27]
The readme currently encourages copy-pasta of `- uses: MatteoH2O1999/setup-python@v1` but the runner is broken on ubuntu-latest for versions that don't include this fix https://github.com/MatteoH2O1999/build-and-install-python/commit/9af67f8154b923b26ad0309a9dd4ca871920dce6

so at minimum it should be `@v2` unless you want to encourage `@latest`

**Comment by MatteoH2O1999** [comment]
Thank you.

Just fixed 😄
