### ISSUE TITLE
Error: No file in xxx matched to [**/requirements.txt or **/pyproject.toml]

### ISSUE THREAD

**Issue by lonnywong** [MatteoH2O1999/setup-python#31]
https://github.com/trzsz/trzsz/actions/runs/6448443268/job/17505711737

My project doesn't have `requirements.txt` or `pyproject.toml`.

**Comment by MatteoH2O1999** [comment]
Caching pip works only with a requirements or a pyproject file. Please remove `cache: pip` and it will work. This is a limitation of the original action
