### ISSUE TITLE
Error message when install old OpenSSL

### ISSUE THREAD

**Issue by kuoruan** [MatteoH2O1999/setup-python#33]
![image](https://github.com/MatteoH2O1999/build-and-install-python/assets/8685618/0a5da3f5-f1a6-44f5-9c8d-f4aa3a76b274)

https://github.com/MatteoH2O1999/build-and-install-python/blob/38708cc2c4c2d517910fa1ceab7a8e0bc28a45b0/src/builder/darwin.ts#L304

Try install with `--build-from-source` ?:
```
brew install --build-from-source ./openssl@1.0.rb
```

**Comment by MatteoH2O1999** [comment]
May I ask you to please fill the correct [form](https://github.com/MatteoH2O1999/setup-python/issues/new/choose)?
From a screenshot I can't really tell what's going on

**Comment by kuoruan** [comment]
Thank you for the reply. Every thing works well. python build succeed. But brew shows this error message.
I want to know if my fix can avoid this error message.

**Comment by MatteoH2O1999** [comment]
It does not. Error message is still there. See [test run](https://github.com/MatteoH2O1999/build-and-install-python/actions/runs/7016708366/job/19088519755?pr=299)
